entry = "main"

[sections]
  text = ".text"
  data = ".data"
  bss = ".bss"
  read_only = ".rdata"

[sizes]
  pointer = 8
  int_lit = 4
  float_lit = 4
  char_lit = 1

[registers]
  biggest_size = 8
  biggest_simd = 128
  instruction_suffix = "sd"
  
  return_register = ["rax", "eax", "ax", "al"]
  return_simd = ["xmm0"]

  basic = [
    ["rbx", "ebx", "bx", "bl"],
    ["rcx", "ecx", "cx", "cl"],
    ["rdx", "edx", "dx", "dl"],
    ["rsi", "esi", "si", "sil"],
    ["rdi", "edi", "di", "dil"],
    ["r8", "r8d", "r8w", "r8b"],
    ["r9", "r9d", "r9w", "r9b"],
    ["r10", "r10d", "r10w", "r10b"],
    ["r11", "r11d", "r11w", "r11b"],
    ["r12", "r12d", "r12w", "r12b"],
    ["r13", "r13d", "r13w", "r13b"],
    ["r14", "r14d", "r14w", "r14b"],
    ["r15", "r15d", "r15w", "r15b"],
  ]

  simds = [
    ["xmm1"],
    ["xmm2"],
    ["xmm3"],
    ["xmm4"],
    ["xmm5"],
    ["xmm6"],
    ["xmm7"],
    ["xmm8"],
    ["xmm9"],
    ["xmm10"],
    ["xmm11"],
    ["xmm12"],
    ["xmm13"],
    ["xmm14"],
    ["xmm15"],
  ]

  stack_pointer = ["rsp", "esp", "sp", "spl"]
  base_pointer = ["rbp", "ebp", "bp", "bpl"]
  
